In [27]:
from  numpy import *

In [28]:
#1 Mathematical operations
a = sin(30)
b = cos(30)
c = tan(30)
print(a , b , c)

a = sin(30*np.pi/180)
b = cos(30*np.pi/180)
c = tan(30*np.pi/180)
print(a , b , c)

a = sin(deg2rad(30))
b = cos(deg2rad(30))
c = tan(deg2rad(30))
print(a , b , c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276
0.49999999999999994 0.8660254037844387 0.5773502691896257
0.49999999999999994 0.8660254037844387 0.5773502691896257


In [29]:
#2 Rounding   التقريب             round() ceil() floor()
a = round(3.68528)
b = round(3.68528,1)
c = round(3.68528,2)
d = round(3.68528,3)
e = round(3.68528,4)
print(a ,"\n", b ,"\n" , c ,"\n" ,d ,"\n" , e)

print("/////////////////////")
a = floor(3.68528)
b = ceil(3.68528)

print(a)
print(b)


4 
 3.7 
 3.69 
 3.685 
 3.6853
/////////////////////
3.0
4.0


In [30]:
# 3 mod , power
a = mod(20,7)
b = power(2,3)

print(a)
print(b)


6
8


In [120]:
#4 Matrices######################################################################################################################
#4.1 Create Matrix##############################################################################################################

a = [2,3,6,5,4,7,8]                                   #list ,
b = [[1,2,3],[5,3,6],[9,6,5]]                         #list ,
c = array(b)                                          #array 
d = array([range(i, i + 3) for i in [2, 4, 6]])
e= array([('x',3,4.2),('y',4,5.3),('z',5,6.3)],
           dtype =[('name','U5'),('number','i2'),
                   ('value','f4')])

print(a)
print(b)
print(c)
print(d)
print("/////////////////////")
print((e['name']))
print(type(e['number'][0]))


[2, 3, 6, 5, 4, 7, 8]
[[1, 2, 3], [5, 3, 6], [9, 6, 5]]
[[1 2 3]
 [5 3 6]
 [9 6 5]]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
/////////////////////
['x' 'y' 'z']
<class 'numpy.int16'>


In [101]:
#4 Matrices#####################################################################################################################
#4.1 Create Matrix##############################################################################################################
# random.uniform(start,and,nb of elements) : floart nb #########################################################################

a = random.uniform(1,10)
b = random.uniform(1,10,20)
print(a)
print('-------------------------')
print(b)
print('-------------------------')

#random.random((l,c)) : array values fom 0m to 1###############################################################################
a =random.random((2,3))
print(a)
print('-------------------------')

#random.normal(start , end ,nb of elements ) : normal distribution#############################################################
a =random.normal(0,1,10)  
print(a)
print('-------------------------')

#random.randint(end,size=nb of elements)#######################################################################################
#random.randint(start,end,size=nb of elements)
#random.randint(start, end, (x, y))  : matrix

a =  random.randint(150,size=7)
print(a)
print('-------------------------')

a = random.randint(0, 10, (3, 3,3))
print(a)
print('-------------------------')

#random.reshape(liste,(l,c))    !!! l*c= nb of elements ########################################################################
a = random.randint(1,60,25)
b = reshape(a,(5,5))
print(a)
print(b)
print('-------------------------')

#random.rand(nb of nb)   de a 1 #################################################################################################
#random.rand(l,c)   matrix de 0 a 1
a = random.rand(15)
b = random.rand(5,3)
print(a)
print(b)
print('-------------------------')

#random.choice(liste,size=x)####################################################################################################
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y)
b = random.choice(y,size = 5)
print(a)
print(b)
print('-------------------------')

#random.shuffle(liste): reordering randomly###############################################################################
random.shuffle(y)
print(y)
print('-------------------------')


5.369650211900951
-------------------------
[1.43663199 8.19463578 7.09830177 5.50241923 6.25202931 6.56999681
 4.86068151 3.65825881 6.95765679 1.73880886 4.49916249 1.35425206
 9.51304536 6.26435488 8.16699509 1.85665352 3.36454959 9.57081556
 1.7620667  8.92299564]
-------------------------
[[0.33977225 0.82180367 0.07178325]
 [0.852419   0.8784402  0.65614669]]
-------------------------
[ 1.49839573  0.10017665 -1.54667038  1.32154342 -1.29322245  0.11904388
 -0.08671439  0.40111056 -0.02680559  0.71411533]
-------------------------
[ 61 141 117  94  38  88  85]
-------------------------
[[[8 1 6]
  [5 5 4]
  [6 3 4]]

 [[5 8 9]
  [2 9 5]
  [8 0 7]]

 [[4 5 2]
  [0 0 5]
  [4 5 6]]]
-------------------------
[ 2 36 20  4  6  5 18 17 11 25  8 37 28 15 17  6 52 50 56 39 53 37 11 47
 35]
[[ 2 36 20  4  6]
 [ 5 18 17 11 25]
 [ 8 37 28 15 17]
 [ 6 52 50 56 39]
 [53 37 11 47 35]]
-------------------------
[0.63945399 0.18776077 0.23602735 0.51455168 0.12795002 0.61488038
 0.56307632 0.364

In [228]:
#4 Matrices#####################################################################################################################
#4.1 Create Matrix##############################################################################################################
#zeros() == random.empty()
#eye()  matrice id +caree  
#full((l,c),nb to fill )  matrice id +caree  

a = zeros((8,3))
b = ones(10)
c = eye(5)
d = full((3, 5), 35)
f= empty((3,2))
j =diag(array([5,12,4,-1,3]))
h =diag(array([5,12,4,-1,3]),k=3)            # add 3l and 3cl

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(f)
print('-------------------------')
print(j)
print('-------------------------')
print(h)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-------------------------
[[35 35 35 35 35]
 [35 35 35 35 35]
 [35 35 35 35 35]]
-------------------------
[[1.00000000e+00 1.11022302e-16]
 [1.00000000e+00 2.77555756e-17]
 [5.55111512e-17 1.00000000e+00]]
-------------------------
[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
-------------------------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0 

In [113]:
#4 Matrices#####################################################################################################################
#4.1 Create Matrix##############################################################################################################
b =arange(18)
print(b)
print('-------------------------')
a =arange(18).reshape(3,6)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
-------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [116]:
#4 Matrices#####################################################################################################################
#4.1 Create Matrix##############################################################################################################
# linesspace(start,end) :50 elements by a certain space

b =linspace(0,30) 
c =linspace(0,100,5)
d =linspace(0,100,27).reshape(3,3,3)
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)


[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
-------------------------
[  0.  25.  50.  75. 100.]
-------------------------
[[[  0.           3.84615385   7.69230769]
  [ 11.53846154  15.38461538  19.23076923]
  [ 23.07692308  26.92307692  30.76923077]]

 [[ 34.61538462  38.46153846  42.30769231]
  [ 46.15384615  50.          53.84615385]
  [ 57.69230769  61.53846154  65.38461538]]

 [[ 69.23076923  73.07692308  76.92307692]
  [ 80.

In [229]:
#4 Matrices#####################################################################################################################
#4.1 Create Matrix##############################################################################################################
# matrix()  reshape()
a = matrix('{} {} ; {} {}'.format(1,2,3,4))
b = matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6))

print(a)
print('-------------------------')
print(b)

[[1 2]
 [3 4]]
-------------------------
[[1 2 3]
 [4 5 6]]


In [140]:
#4 Matrices#####################################################################################################################
#4.2 Manipulate Matrix#######################################################
#a.conditions
a = random.randint(0, 10, (5, 4))
b = count_nonzero(a)
print(a)
print(b)

print('-------------------------')
b = count_nonzero(a>5)
c = count_nonzero(a<8)
print(b)
print(c)
print('-------------------------')

b = count_nonzero(a>5,axis=1)
c = count_nonzero(a<8,axis=0)
print(b)
print(c)
print('-------------------------')

b = any(a>5,axis=1)
print(b)
print('-------------------------')

b = all(a>5)
print(b)
print('-------------------------')

b = a>10
print(b)
print('-------------------------')

c = a[a<9]
print(c)
print('-------------------------')



[[7 9 6 0]
 [0 6 2 4]
 [0 3 3 4]
 [5 5 9 0]
 [0 8 4 6]]
15
-------------------------
7
17
-------------------------
[3 1 0 1 2]
[5 3 4 5]
-------------------------
[ True  True False  True  True]
-------------------------
False
-------------------------
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
-------------------------
[7 6 0 0 6 2 4 0 3 3 4 5 5 0 0 8 4 6]
-------------------------


In [149]:
#4 Matrices#####################################################################################################################
#4.2 Manipulate Matrix#######################################################
#b.comparaision      rtol: tolerance value

a =arange(9).reshape(3,3)
b =arange(9).reshape(3,3)
c = 2*b
d = isclose(a,b,rtol = 0.1)
e = isclose(a,c,rtol = 0.4)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
-------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------------------
[[ True False False]
 [False False False]
 [False False False]]


In [201]:
#4 Matrices#####################################################################################################################
#4.2 Manipulate Matrix#######################################################
#c. math *k * ** +

a =arange(5)
b =empty(5)
multiply(a, 10, out=b)
print(a)
print('-------------------------')
print(b)
print('-------------------------')


a =arange(5)
b =empty(5)
power(a, 4, out=b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')



b = add.reduce(a)                  #EL1+el2+el3
print(b)
print('-------------------------')


a =arange(2,8)                    #EL1*el2*el3
b = multiply.reduce(a)
print(a)
print(b)
print('-------------------------')


b = multiply.outer(a,a)           #M1*M2
print(b)
print('-------------------------')


b = add.accumulate(a)             #not fibonacci
print(a)
print(b)
print('-------------------------')


b = multiply.accumulate(a)
print(b)
print('-------------------------')


a =arange(9)
b = a.reshape(3,3)
c = trace(b)
print(b)
print(c)
print('-------------------------')



a =arange(9)
b = a.reshape(3,3)
c = linalg.det(b)
d = linalg.eig(b)
print(c)
print('-------------------------')
print(d)
print('-------------------------')





[0 1 2 3 4]
-------------------------
[ 0. 10. 20. 30. 40.]
-------------------------
[0 1 2 3 4]
-------------------------
[  0.   1.  16.  81. 256.]
-------------------------
10
-------------------------
[2 3 4 5 6 7]
5040
-------------------------
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]
-------------------------
[2 3 4 5 6 7]
[ 2  5  9 14 20 27]
-------------------------
[   2    6   24  120  720 5040]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12
-------------------------
0.0
-------------------------
(array([ 1.33484692e+01, -1.34846923e+00, -1.15433316e-15]), array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))
-------------------------


In [225]:
#4 Matrices#####################################################################################################################
#4.2 Manipulate Matrix#######################################################
#c. math *k * ** +

a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a+b
d = a-b

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('======================================================================')

from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a*b
d = a/b
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

print('======================================================================')
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = sin(a)
d = b**2
e = log(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('======================================================================')
a =random.randint(1,4, size=9).reshape(3,3)
b =random.randint(1,4, size=9).reshape(3,3)
c = dot(a,b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('======================================================================')
a =random.randint(5,20, size=9).reshape(3,3)
b = sum(a)
c = a.sum()
d = a.sum(axis = 1)
e = a.sum(axis = 0)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('======================================================================')
a =random.randint(5,20, size=9).reshape(3,3)
b = a.mean()              #avrage
c = a.std()               #Standard deviation
d = a.var()               #variance

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

print('======================================================================')
a =random.randint(5,20, size=9).reshape(3,3)
b = corrcoef(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')

print('======================================================================')
a =random.randint(5,20, size=9).reshape(3,3)
b = sort(a,axis=0)
c = sort(a,axis=1)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

print('======================================================================')
a =random.randint(1,4, size=9).reshape(3,3)
b =linalg.inv(a)

c = dot(a,b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

print('======================================================================')






[[10 17  7]
 [ 8 11  7]
 [14  9 14]]
-------------------------
[[ 9 14 12]
 [11 10 16]
 [12  8 10]]
-------------------------
[[19 31 19]
 [19 21 23]
 [26 17 24]]
-------------------------
[[ 1  3 -5]
 [-3  1 -9]
 [ 2  1  4]]
[[10 14 17]
 [ 9 17  5]
 [10 12 12]]
-------------------------
[[ 5 14 16]
 [ 8  8  9]
 [ 9 11 18]]
-------------------------
[[ 50 196 272]
 [ 72 136  45]
 [ 90 132 216]]
-------------------------
[[2.         1.         1.0625    ]
 [1.125      2.125      0.55555556]
 [1.11111111 1.09090909 0.66666667]]
[[17 15 11]
 [ 6  7 16]
 [ 8 11 13]]
-------------------------
[[ 7 19 11]
 [14  8  6]
 [13 17  9]]
-------------------------
[[-0.96139749  0.65028784 -0.99999021]
 [-0.2794155   0.6569866  -0.28790332]
 [ 0.98935825 -0.99999021  0.42016704]]
-------------------------
[[ 49 361 121]
 [196  64  36]
 [169 289  81]]
-------------------------
[[2.83321334 2.7080502  2.39789527]
 [1.79175947 1.94591015 2.77258872]
 [2.07944154 2.39789527 2.56494936]]
[[3 2 3]
 [2 1 2

In [231]:
#4 Matrices#####################################################################################################################
#4.2 Manipulate Matrix#######################################################
#d. math Concatenation

a =arange(4).reshape(2,2)
b =2*arange(4).reshape(2,2)

c = vstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b] , axis = 0)
print('-------------------------')
print(c)

print('======================================================================')
a =arange(4).reshape(2,2)
b =2*arange(4).reshape(2,2)

c = hstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b] , axis = 1)
print('-------------------------')
print(c)




[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1]
 [2 3]
 [0 2]
 [4 6]]
-------------------------
[[ 7  7 18]
 [ 5 11  5]
 [ 9 14 17]
 [18  9 18]
 [ 5 19 15]
 [12 12 16]]
[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1 0 2]
 [2 3 4 6]]
-------------------------
[[19  7  5 19 16 14]
 [14 11 12 13 10 18]
 [12 11  6 14  7 15]]


In [232]:
#4 Matrices#####################################################################################################################
#4.2 Manipulate Matrix#######################################################
#e .Real vs Shadow copy
a =arange(16).reshape(4,4)
print(a)
b = a[:,1:3]
print(b)
print('-------------------------')
a[:,:] = 5
print(a)
print(b)
print('======================================================================')
a =arange(16).reshape(4,4)
print(a)
b = a[:,1:3].copy()
print(b)
print('-------------------------')
a[:,:] = 5
print(a)
print(b)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
-------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5 5]
 [5 5]
 [5 5]
 [5 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
-------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [233]:
#4 Matrices#####################################################################################################################
#4.3 interogation des Matrices#######################################################
#a. info len : nb ol  elements or l /  size : nb of elements / ndim / dtype /  Variance /Covariance


a =arange(12)
b = len(a)
c = a.size
print(b)
print('-------------------------')
print(c)
print('-------------------------')

i = a.reshape(3,4)
j = len(i)
k = i.size
print(j)
print('-------------------------')
print(k)
print('======================================================================')


 
a =arange(24)
b = a.shape
c = a.ndim
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print("nb of dimentions",c)
print('============================')

c = a.reshape(3,4,2)
d = c.shape
e = c.ndim
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print("nb of dimentions",e)
print('-------------------------')

print('======================================================================')
a =array(['a','d','g','h','j'])
b = a.dtype

c = arange(12)
d = c.reshape(3,4)
e = d.dtype
print(b)
print('-------------------------')
print(e)

print('======================================================================')
a =np.random.randint(5,20, size=9).reshape(3,3)
b = np.max(a)
c = np.min(a)
d = np.argmax(a)
e = np.argmin(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('======================================================================')
#  Variance Covariance
a =random.randint(5,20, size=9).reshape(3,3)
b = var(a)
c = cov(a)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)



12
-------------------------
12
-------------------------
3
-------------------------
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
-------------------------
(24,)
-------------------------
nb of dimentions 1
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
-------------------------
(3, 4, 2)
-------------------------
nb of dimentions 3
-------------------------
<U1
-------------------------
int32
[[16  9  5]
 [ 6 19 13]
 [11 19 18]]
-------------------------
19
-------------------------
5
-------------------------
4
-------------------------
2
[[16  6 12]
 [18 19  6]
 [13 16  8]]
-------------------------
22.444444444444443
-------------------------
[[25.33333333 -6.66666667 -9.66666667]
 [-6.66666667 52.33333333 27.83333333]
 [-9.66666667 27.83333333 16.33333333]]


In [ ]:
#4 Matrices#####################################################################################################################
#b.Access #######################################################
a =arange(16).reshape(4,4)
b = a[2][1]
c = a[2,1]

print(a)
print(b)
print(c)

In [230]:
#4 Matrices#####################################################################################################################
#4.3 interogation des Matrices#######################################################
#c.SELECT 
a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)
print('-------------------------')
print('======================================================================')

a =arange(36).reshape(6,6)
c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('======================================================================')
a =arange(36).reshape(6,6)

c = a[3:4,1:5]
d = a[2:,3:]
e = a[:2,:3]
f = a[:,-1]
g = a[-1,:]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)


print('======================================================================')
a =arange(36).reshape(6,6)
c = a[::2,::3]
d = a[::-1,::-1]
e = a[:2:-1,:3:-1]
f = a[2::2,3::3]
g = a[-1::,-1::]
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)



[0 1 2 3 4 5 6 7 8 9]
-------------------------
3
-------------------------
[3 4 5 6 7 8]
-------------------------
[3 5 7]
-------------------------
9
-------------------------
7
-------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[19 20 21 22]]
-------------------------
[[15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
-------------------------
[[0 1 2]
 [6 7 8]]
-------------------------
[ 5 11 17 23 29 35]
-------------------------
[30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 2

In [ ]:
#4 Matrices#####################################################################################################################
#4.3 interogation des Matrices#######################################################
#d.SPLIT 
print('======================================================================')
x = [11,22,33,44,55,66,77,88]
x1, x2, x3 = split(x, (3,6))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (1,5))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (6, 3))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (0, 3))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (4, 0))
print(x1, x2, x3)


In [208]:
#4 Matrices#####################################################################################################################
#4.3 interogation des Matrices#######################################################
#d.MODIFY
a =arange(16).reshape(4,4)
print(a)
print('-------------------------')
a[2,3] = 0
print(a)
print('-------------------------')
a[:,3] = 0 
print(a)
print('-------------------------')
a[2,:] = 0 
print(a)
print('-------------------------')
a[:,:] = 0 
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]
-------------------------
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]]
-------------------------
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 0  0  0  0]
 [12 13 14  0]]
-------------------------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [239]:
#5 Files############################################################################################
fname = 'C:\\Users\\Samira Dihadril\\A) Learn Python For Machine Learning\\files\\textfile1.txt'
dtype1 = dtype([('gender', '|S1'), ('height', 'f8')])
a = loadtxt(fname, dtype=dtype1, skiprows=9, usecols=(1,3))
print(a)
print(a['gender'])
print(a['height'])

[(b'M', 1.82) (b'M', 1.77) (b'F', 1.68) (b'M', 1.72) (b'F', 1.78)
 (b'F', 1.6 ) (b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64)
 (b'M', 1.63) (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 )
 (b'M', 1.97) (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]
[b'M' b'M' b'F' b'M' b'F' b'F' b'M' b'M' b'F' b'F' b'M' b'M' b'M' b'F'
 b'F' b'M' b'F' b'F' b'M']
[1.82 1.77 1.68 1.72 1.78 1.6  1.72 1.83 1.56 1.64 1.63 1.67 1.66 1.59
 1.7  1.97 1.66 1.63 1.69]


In [240]:
#5 Files############################################################################################
#unpack : open all col 
a,b,c = loadtxt('C:\\Users\\Samira Dihadril\\A) Learn Python For Machine Learning\\files\\textfile2.txt',unpack=True,skiprows=3)
print(a)
print(b)
print(c)


[1890. 1900. 1910. 1920. 1930.]
[26.1 25.9 25.1 24.6 24.3]
[22.  21.9 21.6 21.2 21.3]


In [242]:
#5 Files############################################################################################
#generate from text

data = genfromtxt('C:\\Users\\Samira Dihadril\\A) Learn Python For Machine Learning\\files\\textfile3.txt',
                  skip_header=1,
                  dtype=[('student','u8'),('gender','S1'),('black','f8'),('colour','f8')],
                  delimiter=',',
                  missing_values='X')
print(data)


[(1, b'F', 18.72, 31.11) (2, b'F', 21.14, 52.47) (3, b'F', 19.38, 33.9 )]


In [246]:
#6 Polynomials##################################################################################################################
#best fit line y=ax+b
Polynomial = np.polynomial.Polynomial

X= np.array([0,20,40,60,80,100,120,140,160,180])
Y= np.array([10,9,8,7,6,5,4,3,2,1])
points,stats = Polynomial.fit(X,Y,1,full=True)          # 1 :first degree / full = true: all values
print("y=ax+b",points)

y=ax+b poly([ 5.5 -4.5])


In [257]:
#6 Polynomials##################################################################################################################
#best fit line y=ax``+bx+c
Polynomial = np.polynomial.Polynomial

X= np.array([0,20,40,60,80,100,120,140,160,180])
Y= np.array([10,9,8,7,6,5,4,3,2,1])
points,stats = Polynomial.fit(X,Y,2,full=True)          # 2 :first degree / full = true: all values
print("y=ax``+bx+c",points)


print('======================================================================')
x = array([3,6,2,5,4])
y = array([2,3,-9,6,2.5])
z = polyfit(x, y, 2)

print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)
print('-------------------------')

y=ax``+bx+c poly([ 5.50000000e+00 -4.50000000e+00  4.47311763e-16])
[3 6 2 5 4]
-------------------------
[ 2.   3.  -9.   6.   2.5]
-------------------------
[ -1.78571429  17.08571429 -35.3       ]
-------------------------


In [250]:
#6 Polynomials##################################################################################################################
# create plynome poly1d((polynome)) / call poly_NAME(call with nb) / or polyval(plynome,call with nb)

a = poly1d((-7))
b = poly1d((-7,2))
c = poly1d((-7,2,1))
d = poly1d((-7,2,1,3))
e = poly1d((-7,2,1,3,6))


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('================================OR======================================')
a = poly1d((-7,2,1,3,6))
b=a(5)
c=a(0)
d=a(-15)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

print('======================================================================')
a = polyval((1,2),2)
b = polyval((1,2,3),7)
c = polyval((1,2,3,5),-3)
d = polyval((1,2,3,5,-6),12.6)
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)



 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
-------------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
-------------------------
-4079
-------------------------
6
-------------------------
-360939
4
-------------------------
66
-------------------------
-13
-------------------------
29738.769599999992


In [256]:
#6 Polynomials##################################################################################################################
# ROOTS OF POLYNOME
b =roots(poly1d((1,2,3)))
c =roots(poly1d((1,2,3,5)))
d =roots(poly1d((1,2,3,5,12)))
e =roots(poly1d((1,2,3,5,12,22)))

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


        3     2
0.3333 x + 1 x + 3 x
-------------------------
[-1.+1.41421356j -1.-1.41421356j]
-------------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
-------------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
-------------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]


In [252]:
#6 Polynomials##################################################################################################################
# DERIVATION polyder(PLYNOME) / CALL call poly_NAME(call with nb) /

a =polyder(poly1d((1,2,3)))
b =polyder(poly1d((1,2,3)),2)
c =polyder(poly1d((1,2,3)),3)

d =polyder(poly1d((1,2,3,5,12)))
e =polyder(poly1d((1,2,3,5,12)),3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('======================================================================')
a =polyder(poly1d((1,2,3)))
b =polyder(poly1d((1,2,3)),2)
c =polyder(poly1d((1,2,3)),3)

d =polyder(poly1d((1,2,3,5,12)))
e =polyder(poly1d((1,2,3,5,12)),3)

print(a(2))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))



 
2 x + 2
-------------------------
 
2
-------------------------
 
0
-------------------------
   3     2
4 x + 6 x + 6 x + 5
-------------------------
 
24 x + 12
6
-------------------------
2
-------------------------
0.0
-------------------------
1
-------------------------
132


In [254]:
#6 Polynomials##################################################################################################################
# INTEGRATION التكامل 
a =polyint(poly1d((1,2,3)))
b =polyint(poly1d((1,2,3)),2)
c =polyint(poly1d((1,2,3)),3)

d =polyint(poly1d((1,2,3,5,12)))
e =polyint(poly1d((1,2,3,5,12)),3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

print('======================================================================')
a =polyint(poly1d((1,2,3)))
b =polyint(poly1d((1,2,3)),2)
c =polyint(poly1d((1,2,3)),3)
d =polyint(poly1d((1,2,3,5,12)))
e =polyint(poly1d((1,2,3,5,12)),3)
print(a(2))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))



        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
-------------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 2.5 x + 12 x
-------------------------
          7           6        5          4     3
0.004762 x + 0.01667 x + 0.05 x + 0.2083 x + 2 x
12.666666666666666
-------------------------
0.0
-------------------------
24.300000000000004
-------------------------
-10.2
-------------------------
1168.8988095238094


In [260]:
#7 DATES##################################################################################################################
#CREATE DATE 
x = array('2015-07-28', dtype=datetime64)
print(x)
print('-------------------------')
x = datetime64('2015-07-04')
print(x)
print('-------------------------')


2015-07-28
-------------------------
2015-07-04
-------------------------


In [262]:
range(12)

range(0, 12)

In [263]:
arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [269]:
#7 DATES##################################################################################################################
#ADD DAYS / SUBS DAYS /NB OF DAYS BTWN 
x = datetime64('2015-07-04')
y = x + arange(12)
print(x)
print('-------------------------')
print(y)

print('======================================================================')
y = x - arange(12)
print(x)
print('-------------------------')
print(y)

print('======================================================================')
x = datetime64('1999-04-20')
y = datetime64('2021-05-09')
z = (y-x)/366
print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)



2015-07-04
-------------------------
['2015-07-04' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-07-09' '2015-07-10' '2015-07-11' '2015-07-12' '2015-07-13'
 '2015-07-14' '2015-07-15']
2015-07-04
-------------------------
['2015-07-04' '2015-07-03' '2015-07-02' '2015-07-01' '2015-06-30'
 '2015-06-29' '2015-06-28' '2015-06-27' '2015-06-26' '2015-06-25'
 '2015-06-24' '2015-06-23']
1999-04-20
-------------------------
2021-05-09
-------------------------
22 days


In [279]:
#8 Functions ##################################################################################################################
x = fromfunction(lambda i: i**3, (10,))
print(x)
print('-------------------------')

print('======================================================================')
x = fromfunction(lambda i,j: i+j, (4,5))
print(x)
print('-------------------------')

print('======================================================================')
x = fromfunction(lambda i,j,k: (2*i)+(j**2)*k, (2,3,4))
print(x)
print('-------------------------')


print('======================================================================')
def powers(i,j):
    i = i**j
    return i
x = fromfunction(powers, (4,5), dtype=int)
print(x)
print('-------------------------')


print('======================================================================')
m,n = 20, 5
def f(i):
    return (i % n == 0)
x = fromfunction(f, (m,), dtype=int)

print(x)
print('-------------------------')


[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]
-------------------------
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]
-------------------------
[[[ 0.  0.  0.  0.]
  [ 0.  1.  2.  3.]
  [ 0.  4.  8. 12.]]

 [[ 2.  2.  2.  2.]
  [ 2.  3.  4.  5.]
  [ 2.  6. 10. 14.]]]
-------------------------
[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
-------------------------
[ True False False False False  True False False False False  True False
 False False False  True False False False False]
-------------------------


[ True False False False False  True False False False False  True False
 False False False  True False False False False]
-------------------------
